# Generated by Django 3.1.4 on 2021-01-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='crated',
            new_name='created',
        ),
    ]
